name: Sync Organization Repositories

on:
  schedule:
    - cron: '0 0 * * *' # This will run the action once a day; adjust as needed.
  push:
    branches:
      - main # You can adjust this to your preferred branch.
  workflow_dispatch: # Allow manual triggering

env:
  SOURCE_ORG: 'https://gits-15.sys.kth.se/xx'  # GitHub Enterprise organization

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: GitHub Organization Sync-er
      uses: mattwarkentin/github-organization-sync-er@v1.0.2
      with:
        source_org: ${{ env.SOURCE_ORG }}
        target_org: 'https://github.com/xaoexxx'        # GitHub.com organization
        github_token: ${{ secrets.GH_TOKEN }}   # The token you created above
